name: Build selfDPC.Android App

on: [push]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'

    - name: Install dependencies
      run: dotnet restore selfDPC.Android/selfDPC.Android.csproj

    - name: Build
      run: dotnet build --no-restore selfDPC.Android/selfDPC.Android.csproj
      
    - name: Publish
      run: dotnet publish --no-build selfDPC.Android/selfDPC.Android.csproj

    - uses: actions/upload-artifact@v3
      with:
        name: selfDPC.Android
        path: selfDPC.Android/bin/Debug/net6.0-android/publish/*
