name: Build selfDPC.Android App

on: [push]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set default Xamarin SDK versions
      run: |
        $VM_ASSETS/select-xamarin-sdk-v2.sh --mono=6.10 --android=9.0

    - name: Setup .NET Core SDK 5.0.x
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'

    - name: Install dependencies
      run: nuget restore selfDPC.sln

    - name: Build
      run: msbuild selfDPC.Android/selfDPC.Android.csproj /t:PackageForAndroid /p:Configuration=Debug
